services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=db

  genesys-api:
    build:
      context: ./genesys
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/db
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  humana-api:
    build:
      context: ./humana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - genesys-api

volumes:
  mongodb_data: